version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: l1xi_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: l1xi_user
      POSTGRES_PASSWORD: l1xi_password
      POSTGRES_DB: l1xi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /c/Users/apichere/Erziehen/L1xi/database/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U l1xi_user -d l1xi_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for session storage (optional)
  redis:
    image: redis:7-alpine
    container_name: l1xi_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # pgAdmin for database management (development only)
  pgadmin:
    image: dpage/pgadmin4
    container_name: l1xi_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@l1xi.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:

networks:
  default:
    name: l1xi_network